### ISSUE TITLE
Bug or missing instructions?

### ISSUE THREAD

**Issue by vwidmer** [waldbaer/node-red-persistent-values#4]
The only options I see in the storage dropdown are "default" and "memory" there is no file option not sure if this has been removed or if missing something in the setup. Using ver 1.3.1

Thanks

**Comment by waldbaer** [comment]
Hello @vwidmer,

The drop-down represents the actually configured context stores of Node-RED.

I recommend to add the following to the Node-RED settings.json:
```
contextStorage: {
   default: "memoryOnly",
   memoryOnly: { module: 'memory' },
   file: { module: 'localfilesystem' }
}
```
 After a restart hen 'file' should also appear in the drop-down.

See also the Node-RED context storage documentation which is abstracted by the persistent values node:
https://nodered.org/docs/user-guide/context

Please let me know if this solves your issue.
